language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  jobs:
    - DEPS=lowest
    - DEPS=latest
  global:
    - COMPOSER_ARGS="--no-interaction"

jobs:
  allow_failures:
    - php: nightly
      env:
        global:
          - COMPOSER_ARGS="--no-interaction --prefer-lowest"

before_script:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-stable $COMPOSER_ARGS --prefer-lowest ; fi

script:
  - composer test
