language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - DEPS=lowest
  - DEPS=latest

before_script:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --prefer-stable --no-interaction ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-stable --no-interaction --prefer-lowest ; fi

script:
  - composer test
  - composer phpcs
