# Travis CI configuration

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: vendor/bin/phpunit
